version: "3"

volumes:
  node_modules:
services:
  web-dev:
    build:
      context: web
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./web:/src
      - node_modules:/src/node_modules
  db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
