version: '3'

volumes:
  node_modules:
services:
  db:
    image: postgres:16.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
