version: "3"

volumes:
  node_modules:
services:
  web-dev:
    build:
      context: web
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./web:/src
      - node_modules:/src/node_modules
